/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/ui/avatar/avatar.vue')['default']
    AvatarFallback: typeof import('./components/ui/avatar/avatarFallback.vue')['default']
    AvatarImage: typeof import('./components/ui/avatar/avatarImage.vue')['default']
    Badge: typeof import('./components/ui/badge/badge.vue')['default']
    Button: typeof import('./components/ui/button/button.vue')['default']
    FormControl: typeof import('./components/ui/form/formControl.vue')['default']
    FormDescription: typeof import('./components/ui/form/formDescription.vue')['default']
    FormItem: typeof import('./components/ui/form/formItem.vue')['default']
    FormLabel: typeof import('./components/ui/form/formLabel.vue')['default']
    FormMessage: typeof import('./components/ui/form/formMessage.vue')['default']
    GitHub: typeof import('./components/ui/icon/GitHub.vue')['default']
    Google: typeof import('./components/ui/icon/Google.vue')['default']
    Input: typeof import('./components/ui/input/input.vue')['default']
    Label: typeof import('./components/ui/label/label.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./components/SignupForm.vue')['default']
    Spinner: typeof import('./components/ui/icon/Spinner.vue')['default']
  }
}
