/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/button.vue')['default']
    FormControl: typeof import('./components/ui/form/formControl.vue')['default']
    FormDescription: typeof import('./components/ui/form/formDescription.vue')['default']
    FormItem: typeof import('./components/ui/form/formItem.vue')['default']
    FormLabel: typeof import('./components/ui/form/formLabel.vue')['default']
    FormMessage: typeof import('./components/ui/form/formMessage.vue')['default']
    Input: typeof import('./components/ui/input.vue')['default']
    Label: typeof import('./components/ui/label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
